// Command docgen renders docs/resource-types.md from the provider schemas so
// the reference can never drift from the code.
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/udaykishore-resu/strata/internal/provider/gcp"
)

func main() {
	w := os.Stdout
	schemas := gcp.Schemas()
	sort.Slice(schemas, func(i, j int) bool { return schemas[i].Type < schemas[j].Type })
	fmt.Fprintln(w, "# Resource types")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "<!-- Generated by `make docs` from provider schemas. Do not edit. -->")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Type | Description |")
	fmt.Fprintln(w, "|---|---|")
	for _, s := range schemas {
		fmt.Fprintf(w, "| [`%s`](#%s) | %s |\n", s.Type, anchor(s.Type), s.Description)
	}
	for _, s := range schemas {
		fmt.Fprintf(w, "\n## %s\n\n%s\n\n", s.Type, s.Description)
		if s.NameProperty != "" {
			fmt.Fprintf(w, "Physical name: `%s` (generated as `<stack>-<logicalid>-<random>` when omitted, max %d characters).", s.NameProperty, s.Name.MaxLen)
			if s.Labels {
				fmt.Fprint(w, " Ownership labels `strata-stack` and `strata-lid` are added automatically.")
			}
			fmt.Fprint(w, "\n\n")
		}
		fmt.Fprintln(w, "| Property | Type | Required | Replacement | Default | Description |")
		fmt.Fprintln(w, "|---|---|---|---|---|---|")
		names := make([]string, 0, len(s.Properties))
		for n := range s.Properties {
			names = append(names, n)
		}
		sort.Strings(names)
		for _, n := range names {
			p := s.Properties[n]
			def := ""
			if p.Default != nil {
				def = fmt.Sprintf("`%v`", p.Default)
			}
			fmt.Fprintf(w, "| `%s` | %s | %s | %s | %s | %s |\n", n, p.Type, yes(p.Required), yes(p.ForceNew), def, strings.ReplaceAll(p.Description, "|", "\\|"))
		}
		if len(s.Attributes) > 0 {
			attrs := make([]string, 0, len(s.Attributes))
			for a := range s.Attributes {
				attrs = append(attrs, a)
			}
			sort.Strings(attrs)
			fmt.Fprintln(w, "\nAttributes (`getAtt`):")
			fmt.Fprintln(w)
			for _, a := range attrs {
				fmt.Fprintf(w, "- `%s`: %s\n", a, s.Attributes[a])
			}
		}
	}
}

func yes(b bool) string {
	if b {
		return "yes"
	}
	return ""
}

func anchor(t string) string {
	return strings.ReplaceAll(strings.ToLower(t), ":", "")
}
